name: quiz_app
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0




flutter:


  uses-material-design: true

  assets:
    - assets/icons/

  fonts:
    - family: ExpSans
      fonts:
        - asset: assets/fonts/ExpletusSans-Regular.ttf
          weight: 400
    - family: DMSans
      fonts:
          - asset: assets/fonts/DMSans-Medium.ttf
            weight: 500
          - asset: assets/fonts/DMSans-Bold.ttf
            weight: 700

    #         style: italic
    #   - family: Trajan Pro
    #     fonts:
    #       - asset: fonts/TrajanPro.ttf
    #       - asset: fonts/TrajanPro_Bold.ttf
    #         weight: 700
    #

